### ISSUE TITLE
LZ，为什么我运行后，不能生成data.json啊？

### ISSUE THREAD

**Issue by sunfeng90** [iNuanfeng/node-spider#1]
爬取到2221条的时候，就不爬取了。也不会爬取最后一条，也不会生成data.json，你调试了吗？

**Comment by iNuanfeng** [comment]
刚测试了一下，是可以的。
你说的应该是爬取车系的时候，我总共爬取了2222条，说明是有一个页面你那边爬取的时候卡在那了。
程序目前是必须把这一级所有数据全部爬取过来，才能进行下一级车型爬取的。
要不你就等网络好点了再试试，或者你给他加个判断，超过多少时间就放弃这个页面。

**Comment by sunfeng90** [comment]
貌似我尝试使用node save-mysql也没有用哦，发现package.json里面没有安装类似save-mysql的包啊
