### ISSUE TITLE
LZ，已经帮你解决存入MongoDB问题，并Fork你的代码。

### ISSUE THREAD

**Issue by sunfeng90** [iNuanfeng/node-spider#3]
1、具体代码在：https://github.com/sunfeng90/node-spider/blob/autohome/app.js
     你差分一下代码，并合并到你的代码吧

2、可以在你的基础上继续维护和开发吗？

**Comment by iNuanfeng** [comment]
当然可以 : )

**Comment by sunfeng90** [comment]
我提交一个pull request，你合并到你代码中吧！

我接下来准备：
1）引入HighChart，将爬取的数据显示在页面上。
2）引入单元测试

**Comment by sunfeng90** [comment]
如果可以，把我名字和git地址写到package.json中，谢谢

**Comment by iNuanfeng** [comment]
已合并 : )

**Comment by sunfeng90** [comment]
好的
